# Generated by Django 4.1.2 on 2022-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
